server:
  port: 8082
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservices
  application:
    name: HOTEL-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka

